name = 'Theme name'
license = 'MIT'
licenselink = 'https://github.com/calfeche13/Sayun/blob/main/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/calfeche13/Sayun'

# If you have a running demo of the theme
demosite = 'tba'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

[author]
  name = 'Chosen Realm Alfeche'
  homepage = 'N/A'
